# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepoll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(default='Anonymous', max_length=30),
        ),
    ]
