# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepoll', '0002_participant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
