# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-09 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepoll', '0003_auto_20161008_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='pid',
            field=models.CharField(default='AbcD', max_length=4),
        ),
    ]
