# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepoll', '0004_poll_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='submitter',
            field=models.CharField(default='Anonymous', max_length=20),
        ),
    ]
