# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-20 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepoll', '0005_poll_submitter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('registration_date', models.DateField(verbose_name='registration date')),
            ],
        ),
    ]
