# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-31 04:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepoll', '0006_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='last_access_token',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(max_length=60),
        ),
    ]
