# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepoll', '0007_auto_20161230_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='image_link',
            field=models.CharField(default='', max_length=300),
        ),
    ]
