# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-26 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onepoll', '0009_poll_poll_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='category',
            field=models.CharField(default='Other', max_length=50),
        ),
    ]
