# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 02:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_participant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='views',
        ),
    ]
