# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-19 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='public_poll',
            field=models.IntegerField(default=1, verbose_name=1),
            preserve_default=False,
        ),
    ]
